urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'glx.views.home', name='home'),
    # url(r'^glx/', include('glx.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    (r'^$', 'asset.views.index'),
    
    # asset detail page with comment stream
    (r'^asset/(?P<asset_id>\d+)/$', 'asset.views.detail'),
    
    # add new asset
    (r'^asset/new/', 'asset.views.new'),
    
    # get all assets as kml
    (r'^asset/kml/', 'asset.views.kml'),
    
)

asset/models.py
from django.contrib.gis.db import models
from django.forms import ModelForm, HiddenInput, TextInput, RadioSelect

# workaround for South custom fields issues 
try:
    from south.modelsinspector import add_introspection_rules
    add_introspection_rules([], ['^django\.contrib\.gis\.db\.models\.fields\.PointField'])
except ImportError:
    pass

ASSET_CATEGORIES = (
    ('p', 'Preservation'),
    ('c', 'Change'),
)

class Asset(models.Model):
    title = models.CharField('Asset Title', max_length=100,)
    category = models.CharField('Asset Category', max_length=1, default='p', choices=ASSET_CATEGORIES)
    ip = models.IPAddressField('IP Address', blank=True, null=True)
    # GeoDjango
    location = models.PointField(geography=True, blank=True, null=True, default='POINT(0 0)') # default SRS 4326
    objects = models.GeoManager()
    
    def __unicode__(self):
        return u'%s' % (self.id)
    
    def get_absolute_url(self):
        return "/asset/%i/" % self.id

class AssetForm(ModelForm):
    
    class Meta:
        model = Asset
        exclude = ('ip',)
        widgets = {
            'title': TextInput(attrs={'size': '100',}),
            'category': RadioSelect(),
            'location': HiddenInput(),         
        }

asset/views.py
from django.conf import settings
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.contrib.gis.shortcuts import render_to_kml

from asset.models import Asset, AssetForm

# Create your views here.
def index(request):
    
    assets  = Asset.objects.all()
    
    return render_to_response('asset/index.html', 
            {'assets' : assets,
             'MEDIA_URL': settings.MEDIA_URL,},
            context_instance=RequestContext(request)
        )
    
def new(request):
    
    if request.method == 'POST':
        form = AssetForm(request.POST)
        if form.is_valid():
            entry = form.save(commit=False)
            entry.ip = request.META['REMOTE_ADDR']
            entry.save()
            return render_to_response('asset/thanks.html',
                                      {'asset': entry,
                                       'MEDIA_URL': settings.MEDIA_URL,},
                                      context_instance=RequestContext(request))            
    else:
        form = AssetForm()
        
    return render_to_response('asset/new.html', 
                              {'form': form, 
                               'MEDIA_URL': settings.MEDIA_URL,}, 
                               context_instance=RequestContext(request))   
    
def detail(request, asset_id):
    asset = Asset.objects.get(pk=asset_id)
    return render_to_response('asset/detail.html',
                            {'asset': asset,
                             'MEDIA_URL': settings.MEDIA_URL,},
                            context_instance=RequestContext(request)) 
    
def kml(request):
     assets  = Asset.objects.kml()
     return render_to_kml('asset/assets.kml', 
                            {'assets' : assets,
                             'MEDIA_URL': settings.MEDIA_URL,},
                            context_instance=RequestContext(request)) 

templates/asset/detail.html
{% extends "base.html" %}
{% load disqus_tags %}



{% block style %}

#map_canvas {
	width: 100%; 
	height: 400px;
	margin-bottom: 18px;
}

{% endblock %}

{% block javascript %}

<script src="http://ajax.aspnetcdn.com/ajax/jquery/jquery-1.5.2.min.js" type="text/javascript"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>

<script type="text/javascript">

$(document).ready(function() {alert	
	var station = new google.maps.LatLng(42.4166293422, -71.1281383942);
	
	var mapOptions = {
		zoom: 14,
		mapTypeId: google.maps.MapTypeId.ROADMAP,
		center: station
	};
 
	var map = new google.maps.Map(document.getElementById("map_canvas"),
		mapOptions);
		
	var marker_station = new google.maps.Marker({
		map: map,
		title: "Proposed Green Line Station",
		position: station,
		icon: "{{ MEDIA_URL }}img/train.png"
	});
	
	var shadow = new google.maps.MarkerImage("{{ MEDIA_URL }}img/shadow.png",
		new google.maps.Size(38.0, 34.0),
		new google.maps.Point(0, 0),
		new google.maps.Point(10, 34)
    );
	
	var asset = new google.maps.LatLng({{ asset.location.y }}, {{ asset.location.x }});
	
	var markerAsset = new google.maps.Marker({
		position: asset, 
		map: map, 
		title:"{{ asset.title }}",
		icon: "{{ MEDIA_URL }}img/marker_{{ asset.category }}.png",
		shadow: shadow
	});
	
	function toggleBounce() {
		if (markerAsset.getAnimation() != null) {
			markerAsset.setAnimation(null);
		} else {
			markerAsset.setAnimation(google.maps.Animation.BOUNCE);
		}
	}    
});

</script>

{% endblock %}

{% block body %}

<div class="prepend-2 span-20 append-2 last">

<h2>{{ asset.title }}</h2>

<p class="large">Catgegory: <strong>{{ asset.get_category_display }}</strong></p>

<div id="map_canvas"></div>

{% disqus_dev %}
{% set_disqus_developer 1 %}

{% set_disqus_identifier "asset_" asset.id %}
{% set_disqus_url asset.get_absolute_url %}
{% set_disqus_title asset.title %}

{% disqus_show_comments %}

</div>

{% endblock %}

templates/asset/index.html
{% extends "base.html" %}

{% block style %}

#map_canvas {
	width: 100%; 
	height: 400px;
	margin-bottom: 9px;
}

{% endblock %}

{% block javascript %}

<script src="http://ajax.aspnetcdn.com/ajax/jquery/jquery-1.5.2.min.js" type="text/javascript"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>

<script type="text/javascript">

$(document).ready(function() {
	
	var station = new google.maps.LatLng(42.4166293422, -71.1281383942);
	
	var mapOptions = {
		zoom: 14,
		mapTypeId: google.maps.MapTypeId.ROADMAP,
		center: station
	};
 
	var map = new google.maps.Map(document.getElementById("map_canvas"),
		mapOptions);
		
	var marker_station = new google.maps.Marker({
		map: map,
		title: "Proposed Green Line Station",
		position: station,
		icon: "{{ MEDIA_URL }}img/train.png"
	});
    
	var shadow = new google.maps.MarkerImage("{{ MEDIA_URL }}img/shadow.png",
		new google.maps.Size(38.0, 34.0),
		new google.maps.Point(0, 0),
		new google.maps.Point(10, 34)
    );
    
    {% for asset in assets %}
    	var latlng_{{ asset.id }} = new google.maps.LatLng({{ asset.location.y }}, {{ asset.location.x }});
    	var info_{{ asset.id }} = new google.maps.InfoWindow({
			content: "<strong>{{ asset.title }}</strong> ({{ asset.get_category_display }}) <br><a href='{{ asset.get_absolute_url }}'>Join the discussion!</a>"
		});
		var marker_{{ asset.id }} = new google.maps.Marker({
			position: latlng_{{ asset.id }},
    		map: map,
    		title:"{{ asset.title }}",
    		icon: "{{ MEDIA_URL }}img/marker_{{ asset.category }}.png",
    		shadow: shadow
		});
    	google.maps.event.addListener(marker_{{ asset.id }}, 'click', function() {
			info_{{ asset.id }}.open(map,marker_{{ asset.id }});
		});
    {% endfor %}

	// kml layer from /assets/kml/
	// var assets = new google.maps.KmlLayer('/asset/kml/');
	// assets.setMap(map);
   
});

</script>

{% endblock %}

{% block body %}

<div class="prepend-2 span-20 append-2 last">
	
<h2>What is an "asset"?</h2>

<p>As the Metropolitan Area Planning Council (MAPC) moves forward in developing a vision for the area surrounding the potential 
	Mystic Valley Parkway Green Line station, it is important that residents of surrounding communities are involved in identifying 
	key community resources. MAPC will refer to these key resources as "assets".</p>

<p>Assets will be grouped under two categories for this mapping exercise: "Preservation" <img src="{{ MEDIA_URL }}img/marker_p.png" height="18" alt="Preservation"> 
	and "Change" <img src="{{ MEDIA_URL }}img/marker_c.png" height="18" alt="Change">. Preservation refers to assets 
	which are of value to residents and should be preserved if the Green Line comes to Mystic Valley Parkway. Change refers to assets 
	which offer opportunities for change and can have a positive impact for residents if the Green Line is extended.</p>
	
<p>MAPC is looking for specific examples of assets. These could include:
	<ul>
		<li>Buildings (i.e. U-Haul, 200 Boston Avenue, Whole Foods)</li>
		<li>Parks or open space (i.e. Mystic River, Dilboy Field)</li>
		<li>Transportation facilities (i.e. sidewalks, roadways, intersections)</li>
	</ul>	
</p>

<p>We are not looking for general categories of assets such as housing or transportation. If you would like to see more housing or 
	more commercial development or better sidewalks, please choose specific locations. All general comments can be submitted to 
	MAPC at <a href="mailto:glx@mapc.org?subject=General comment">glx@mapc.org</a>.</p>

<h2>Why are we mapping assets?</h2>

<p>The input provided through this website and at the public meeting on <a href="http://www.mapc.org/smart-growth/green-line-extension" title="Green Line Extension">May 17th</a> will be used by MAPC to develop different 
	land use and development scenarios for the future around the potential Green Line station. By working with the public to 
	map assets, MAPC will have a better understanding of what the public would like to see preserved in the area and what could 
	be changed. This input will feed directly into the scenario modeling exercises that are planned for the upcoming fourth 
	meeting for this project.</p>

<div id="map_canvas"></div>

<p class="large loud" style="text-align:center"><a href="/asset/new" title="Add new asset"><strong>Add new asset</strong></a></p>

<h3>Instructions for mapping assets</h3>

<ol>
<li>Click on <a href="/asset/new" title="Add new asset">Add New Asset</a> under the map.</li>
<li>Drag the red asset marker to the location of the asset you wish to map.</li>
<li>You can zoom in or out or pan using your mouse or the controls on the left side of the map.  You can also toggle between the road map and a satellite image.</li>
<li>After you have placed your asset marker, please provide a title for the asset in the title box.</li>
<li>Select whether the asset should be a preservation or change marker.</li>
<li>Click the "Add!" button.</li>
<li>If you wish to add a new comment to your asset, click the “add a new comment” link.</li>
<li>If you wish to another asset, click on the "add another asset” link.</li>
</ol>

<p class="loud"><strong>If the asset you want to map already exists, you can simply post a new comment and join the discussion by clicking on the marker instead of 
	re-mapping the asset.</strong></p>


</div>

{% endblock %}

templates/asset/new.html
{% extends "base.html" %}

{% block style %}

.form-row input[type=text] {
	margin-left: 18px;
}

.form-row ul li {
	list-style: none;
	display: inline;
}

#map_canvas {
	width: 100%; 
	height: 400px;
	margin-bottom: 18px;
}

h3 {
	margin-top: 18px;
}

{% endblock %}

{% block javascript %}

<script src="http://ajax.aspnetcdn.com/ajax/jquery/jquery-1.5.2.min.js" type="text/javascript"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>

<script type="text/javascript">

$(document).ready(function() {

	var station = new google.maps.LatLng(42.4166293422, -71.1281383942);
	
	var mapOptions = {
		zoom: 14,
		mapTypeId: google.maps.MapTypeId.ROADMAP,
		center: station
	};
 
	var map = new google.maps.Map(document.getElementById("map_canvas"),
		mapOptions);
		
	var marker_station = new google.maps.Marker({
		map: map,
		title: "Proposed Green Line Station",
		position: station,
		icon: "{{ MEDIA_URL }}img/train.png"
	});
	
	var asset = new google.maps.LatLng(42.4166293422, -71.1281383942);
	
	var markerAsset = new google.maps.Marker({
		position: asset,
		draggable:true,
		animation: google.maps.Animation.DROP, 
		map: map, 
		title:"New Asset"
	});
	
	// animation
	google.maps.event.addListener(markerAsset, 'click', toggleBounce);
	// track marker dragging		
	google.maps.event.addListener(markerAsset, 'dragend', function() {
		// write loc coord to hidden geometry field (in WGS84)
		$("#id_location").val("POINT (" + markerAsset.position.lng() + " " +  markerAsset.position.lat() + ")");
		// validate location
		validation["marker"] = true;		
	});
	
	function toggleBounce() {
		if (markerAsset.getAnimation() != null) {
			markerAsset.setAnimation(null);
		} else {
			markerAsset.setAnimation(google.maps.Animation.BOUNCE);
		}
	}
	
	// form validation
	var validation = {
		"formerror":{% if formerror %} true {% else %} false {% endif %},
		"marker": false // location not set
	};
	
	$("#assetform").submit(function() {
		
		// alert($("#id_location").val());
		
		// check location field
		if ($("#id_location").val() === "POINT(0 0)") {
			validation.marker = false;
		} else {
			// required for django validation error page-reload
			validation.marker = true;
		}
		
      	// no location provided, harder to check with django form validation
		if (validation.marker === false) {
			alert("Please drag the marker to your asset location.");
	      	return false;
		}

   });    
});

</script>

{% endblock %}

{% block body %}

<div class="prepend-2 span-20 append-2 last">

<h2>Add new asset</h2>

<form id="assetform" action="." method="post">

{% csrf_token %}

<fieldset>
	
	<p>Please drag the marker to your asset location:</p>
	<div id="map_canvas"></div>
	
	{{ form.location }}
	
	<div class="form-row">
	{% if form.title.errors %}
	<div class="error">
		{% for error in form.title.errors %}
			{{ error|escape }}<br>
		{% endfor %}
		<label class="large">Please provide an asset title:</label><br> {{ form.title }}
	</div>
	{% else %}
	<label class="large">Please provide an asset title:</label><br> {{ form.title }}
	{% endif %}	
	</div>
	
	<div class="form-row">
		
		{{ form.category.errors }}
		<label class="large">Please select an asset category:</label> {{ form.category }}
		
	</div>
	
</fieldset>

<input type="submit" value="Add!" />
</form>

<h3>Instructions for mapping assets</h3>
<ol>
<li>Drag the red asset marker to the location of the asset you wish to map.</li>
<li>You can zoom in or out or pan using your mouse or the controls on the left side of the map.  You can also toggle between the road map and a satellite image.</li>
<li>After you have placed your asset marker, please provide a title for the asset in the title box.</li>
<li>Select whether the asset should be a preservation or change marker.</li>
<li>Click the "Add!" button.</li>
<li>If you wish to add a new comment to your asset, click the “add a new comment” link.</li>
<li>If you wish to another asset, click on the "add another asset” link.</li>
</ol>

</div>

{% endblock %}

templates/asset/thanks.html
{% extends "base.html" %}

{% block style %}

h2, p {
	text-align: center;
}

{% endblock %}

{% block body %}

<div class="prepend-2 span-20 append-2 last">

<h2>Thank you!</h2>

<p>Your asset "<strong>{{ asset.title }}</strong>" has been added to the map.</p>
	
<p><a href="/asset/{{ asset.id }}" title="{{ asset.title }}">Add a new comment</a> to it or 
	<a href="/asset/new/" title="Add new asset">add another asset</a> to the map</p>

</div>

{% endblock %}

templates/base.html
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %}GLX Assets</title>
	<meta name="description" content="Green Line Extension Asset Mapping">
	<meta name="keywords" content="Boston, Metro, Planning, Participation, Green Line, Transportation, Public, Meeting">
	<meta name="author" content="MAPC">
        
    <!-- geotags -->
	<meta name="DC.title" content="GLX Assets"> 
	<meta name="geo.placename" content="Boston">
	<meta name="geo.position" content="42.4166293422;-71.1281383942">
	<meta name="geo.region" content="US-MA">
	<meta name="ICBM" content="42.4166293422;-71.1281383942">
	
	<link rel="stylesheet" href="{{ MEDIA_URL }}css/blueprint-css/blueprint/screen.css" type="text/css" media="screen, projection">
	<link rel="stylesheet" href="{{ MEDIA_URL }}css/blueprint-css/blueprint/print.css" type="text/css" media="print">
	<!--[if lt IE 8]>
	<link rel="stylesheet" href="{{ STATIC_URL }}css/blueprint-css/blueprint/ie.css" type="text/css" media="screen, projection">
	<![endif]-->
	
	<style type="text/css">
	
	#header{
		text-align: center;
	}
	
	#footer {
		text-align: center;
	}
	
	{% block style %}{% endblock %}
	</style>
	
	{% block javascript %}{% endblock %}
	
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-5547782-12']);
	  _gaq.push(['_trackPageview']);
	
	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	
	</script>
	
</head>
<body>
	
	<div id="wrap">
		<div class="container">
		
		<div id="header" class="prepend-2 span-20 append-2 append-bottom prepend-top last">
			<a href="/" title="Mystic Valley Parkway Community Visioning Process"><img src="{{ MEDIA_URL }}img/glx-logo.png" alt="Mystic Valley Parkway Community Visioning Process" /></a>
			<h1>Asset Mapping</h1>
		</div>
		
		{% block body %}{% endblock %}
		
		<div id="footer" class="prepend-2 span-20 append-2 append-bottom prepend-top small">
			<p>
				{% blocktrans %}
				Questions? Please contact{% endblocktrans %} <a href="mailto:glx@mapc.org?subject=Greenline Asset Mapping question">glx@mapc.org</a><br>
				&copy; <a href="http://www.mapc.org" title="Metropolitan Area Planning Council">MAPC</a> 2011
			</p>	
		</div>
		
		</div>
	</div>
	
</body>
</html>